import { useState, useMemo, useCallback, useEffect } from "react";
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from "recharts";
import { createClient } from "@supabase/supabase-js";

var SB_URL='https://oumgqrfqxljcnkbnqdmg.supabase.co';
var SB_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91bWdxcmZxeGxqY25rYm5xZG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5NDcxNTcsImV4cCI6MjA5MTUyMzE1N30.YmJmaZy_4TacpH8Lw9j0OxoKm5BJ7qiMvIsTZBabRTg';
var sb=createClient(SB_URL,SB_KEY);

function simpleHash(s){var h=0;for(var i=0;i<s.length;i++){h=((h<<5)-h)+s.charCodeAt(i);h=h&h}return String(h)}
function pCSVL(l){var f=[],c='',q=false;for(var i=0;i<l.length;i++){var ch=l[i];if(ch==='"'){if(q&&i+1<l.length&&l[i+1]==='"'){c+='"';i++}else q=!q}else if(ch===','&&!q){f.push(c);c=''}else c+=ch}f.push(c);return f}
function fixEnc(s){if(!s)return'';var r=s;try{var P=[['√©','é'],['√®','è'],['√¨','è'],['√ê','ê'],['√†','à'],['√¢','â'],['√Æ','î'],['√ô','ô'],['√ª','û'],['√´','ë'],['√Ø','ï'],['√á','á'],['√ß','ç'],['√±','ñ'],['√ü','ü'],['√Å','Å'],['¬∞','°'],['‚Äì','–'],['‚Äî','—'],['‚Äú','"'],['‚Äù','"'],['‚Äô',"'"],['‚Äò',"'"],['‚Ä¶','…']];for(var i=0;i<P.length;i++){if(r.indexOf(P[i][0])!==-1)r=r.split(P[i][0]).join(P[i][1])}}catch(e){}return r}
function csvToPipe(raw){try{var cl=fixEnc(raw).replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').replace(/\r/g,'\n');var lines=cl.split('\n').filter(function(l){return l.trim()});if(lines.length<2)return{pipe:'',w:[],e:['No data rows'],count:0};var hdr=pCSVL(lines[0]).map(function(h){return h.trim().replace(/^\uFEFF/,'')});var hi={};hdr.forEach(function(h,i){hi[h]=i;var lc=h.toLowerCase();if(hi[lc]===undefined)hi[lc]=i});var gi=function(c){if(hi[c]!==undefined)return hi[c];var lc=c.toLowerCase();if(hi[lc]!==undefined)return hi[lc];for(var k in hi){if(k.toLowerCase()===lc)return hi[k]}return undefined};var nI=gi('Name'),yI=gi('Year'),wI=gi('Watched Date'),rI=gi('Rating'),rwI=gi('Rewatch'),tI=gi('Tags');if(nI===undefined||yI===undefined||wI===undefined)return{pipe:'',w:[],e:['Missing columns'],count:0};var ent=[];for(var i=1;i<lines.length;i++){var f=pCSVL(lines[i]);var gf=function(idx){return idx!==undefined&&idx<f.length?(f[idx]||'').trim():''};var nm=gf(nI),yr=gf(yI),wd=gf(wI),rt=gf(rI),rw=gf(rwI),tr=gf(tI);if(!nm||!wd)continue;var tg=tr.split(',').map(function(t){return t.trim().toLowerCase()}).filter(Boolean);ent.push({wd:wd,nm:nm,yr:yr,rt:rt,rw:rw==='Yes'?'R':'',tg:tg.join(',')})}ent.sort(function(a,b){return a.wd<b.wd?-1:a.wd>b.wd?1:0});return{pipe:ent.map(function(e){return e.wd+'|'+e.nm+'|'+e.yr+'|'+e.rt+'|'+e.rw+'|'+e.tg}).join('\n'),w:[],e:[],count:ent.length}}catch(err){return{pipe:'',w:[],e:['Error: '+String(err)],count:0}}}
function parsePipe(raw){if(!raw||!raw.trim())return[];return raw.trim().split('\n').filter(function(l){return l.trim()}).map(function(l){var p=l.split('|');var tags=p[5]?p[5].split(',').map(function(t){return t.trim()}).filter(Boolean):[];var r=p[3]?p[3].trim():'';return{date:p[0],name:p[1],year:parseInt(p[2]),rating:r&&!isNaN(parseFloat(r))?parseFloat(r):null,rewatch:p[4]==='R',tags:tags}}).filter(function(e){return e.tags.indexOf('series')===-1&&e.tags.indexOf('short')===-1})}

var CATS=['platform_paid','platform_free','platform_rental','sub_venue','indie_venue','friend','taste','meta','price'];
var CI={platform_paid:{l:'📺 Paid Platform',c:'text-blue-400',bg:'bg-blue-900/30 border-blue-800'},platform_free:{l:'📺 Free Platform',c:'text-cyan-400',bg:'bg-cyan-900/30 border-cyan-800'},platform_rental:{l:'📀 Rental',c:'text-orange-400',bg:'bg-orange-900/30 border-orange-800'},sub_venue:{l:'🎬 Sub Venue',c:'text-emerald-400',bg:'bg-emerald-900/30 border-emerald-800'},indie_venue:{l:'🎭 Indie Venue',c:'text-amber-400',bg:'bg-amber-900/30 border-amber-800'},friend:{l:'👥 Friend',c:'text-pink-400',bg:'bg-pink-900/30 border-pink-800'},taste:{l:'🏷️ Taste',c:'text-purple-400',bg:'bg-purple-900/30 border-purple-800'},meta:{l:'⚙️ Meta',c:'text-gray-400',bg:'bg-gray-800/50 border-gray-700'},price:{l:'💰 Price',c:'text-yellow-400',bg:'bg-yellow-900/30 border-yellow-800'}};
var MS=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
var MF=['January','February','March','April','May','June','July','August','September','October','November','December'];
var YC={'2021':'#f87171','2022':'#fbbf24','2023':'#34d399','2024':'#60a5fa','2025':'#a78bfa','2026':'#f472b6'};
var CLR=['#34d399','#60a5fa','#f472b6','#fbbf24','#a78bfa','#fb923c'];
var DSUBS=[{id:'rat',name:'Rat+',platforms:['canal','netflix','hbo','paramount'],periods:[{from:'2021-10',to:'',price:40}]},{id:'disney',name:'Disney+',platforms:['disney'],periods:[{from:'2023-01',to:'',price:9}]},{id:'mubi',name:'Mubi',platforms:['mubi'],periods:[{from:'2021-11',to:'',price:11}]},{id:'prime',name:'Prime Video',platforms:['prime'],periods:[{from:'2022-01',to:'',price:7}]},{id:'theater',name:'Pathé/UGC Pass',platforms:['_theater_sub'],periods:[{from:'2023-07',to:'',price:22}]}];

function getDn(t,reg){var e=reg[t];return(e&&e.dn)?e.dn:t}
function getCat(t,reg){var e=reg[t];return e?e.cat:null}
function isPlatform(cat){return cat==='platform_paid'||cat==='platform_free'||cat==='platform_rental'}
function gP(tags,reg){for(var i=0;i<tags.length;i++){var c=getCat(tags[i],reg);if(isPlatform(c))return getDn(tags[i],reg);if(c==='sub_venue'||c==='indie_venue')return'Theater'}return'Other'}
function gV(tags,reg){for(var i=0;i<tags.length;i++){var c=getCat(tags[i],reg);if(c==='sub_venue'||c==='indie_venue')return tags[i]}return null}
function gC(tags,reg){var r=[];for(var i=0;i<tags.length;i++){if(getCat(tags[i],reg)==='friend')r.push(getDn(tags[i],reg))}return r}
function gTP(tags,reg){for(var i=tags.length-1;i>=0;i--){if(getCat(tags[i],reg)==='price')return parseInt(tags[i])/100}return null}
function rC(r){if(!r||r===0)return'#9ca3af';if(r<=1)return'#b91c1c';if(r<=1.5)return'#dc2626';if(r<=2)return'#ea580c';if(r<=2.5)return'#d97706';if(r<=3)return'#ca8a04';if(r<=3.5)return'#65a30d';if(r<=4)return'#16a34a';if(r<=4.5)return'#15803d';return'#166534'}
function fmtM(ym){var p=ym.split('-');return MF[parseInt(p[1])-1]+' '+p[0]}
function fY(v,t){if(v==null||isNaN(v))return null;if(t==='abs'){var r=Math.round(v);if(!r)return null;return(r>0?'+':'')+r}if(t==='r'){if(Math.abs(v)<0.005)return null;return(v>0?'+':'')+v.toFixed(2)}if(t==='pp'){var r2=Math.round(v);if(!r2)return null;return(r2>0?'+':'')+r2+'pp'}return null}
function mBt(f,t){var fp=f.split('-').map(Number),tp=t.split('-').map(Number);return(tp[0]-fp[0])*12+(tp[1]-fp[1])+1}
function agg(arr,kf){var m={};arr.forEach(function(e){var k=kf(e);if(!m[k])m[k]={c:0,s:0,r:0};m[k].c++;if(e.rating!==null){m[k].s+=e.rating;m[k].r++}});return Object.keys(m).map(function(n){var v=m[n];return{name:n,Films:v.c,Avg:v.r?parseFloat((v.s/v.r).toFixed(2)):0}})}
function getWeekMon(ds){var d=new Date(ds+'T12:00:00');var day=d.getDay();d.setDate(d.getDate()-(day===0?6:day-1));return d.toISOString().slice(0,10)}
function calcStreaks(films){var dates=Array.from(new Set(films.map(function(e){return e.date}))).sort();if(!dates.length)return{day:0,week:0,wr:''};var ds=new Set(dates),last=dates[dates.length-1],dayS=0,cd=new Date(last+'T12:00:00');while(ds.has(cd.toISOString().slice(0,10))){dayS++;cd.setDate(cd.getDate()-1)}var weeks=new Set(dates.map(function(d){return getWeekMon(d)})),weekS=0,cm=new Date(getWeekMon(last)+'T12:00:00');while(weeks.has(cm.toISOString().slice(0,10))){weekS++;cm.setDate(cm.getDate()-7)}var ws=new Date(cm);ws.setDate(ws.getDate()+7);var we=new Date(getWeekMon(last)+'T12:00:00');we.setDate(we.getDate()+6);var wr='';if(weekS>0){var a=ws.toISOString().slice(0,10).split('-').map(Number),b=we.toISOString().slice(0,10).split('-').map(Number);wr=MS[a[1]-1]+' '+a[2]+', '+a[0]+' – '+MS[b[1]-1]+' '+b[2]+', '+b[0]}return{day:dayS,week:weekS,wr:wr}}
function calcWrapped(all,reg){return Array.from(new Set(all.map(function(e){return e.date.slice(0,4)}))).sort().map(function(yr){var f=all.filter(function(e){return e.date.indexOf(yr)===0}),rated=f.filter(function(e){return e.rating!==null}),avg=rated.length?rated.reduce(function(s,e){return s+e.rating},0)/rated.length:0;var cc={};f.forEach(function(e){gC(e.tags,reg).forEach(function(n){cc[n]=(cc[n]||0)+1})});var topC=null,topCC=0;Object.keys(cc).forEach(function(n){if(cc[n]>topCC){topCC=cc[n];topC=n}});var mc={};f.forEach(function(e){mc[e.date.slice(5,7)]=(mc[e.date.slice(5,7)]||0)+1});var topMo=null,topMC=0;Object.keys(mc).forEach(function(m){if(mc[m]>topMC){topMC=mc[m];topMo=m}});var thN=f.filter(function(e){return gP(e.tags,reg)==='Theater'||gV(e.tags,reg)!==null}).length;return{yr:yr,total:f.length,avg:avg,topC:topC,topCC:topCC,topMo:topMo?MF[parseInt(topMo)-1]:null,topMC:topMC,thPct:f.length?Math.round(thN/f.length*100):0}})}
function calcDQ(all,reg){var nV=[],nS=[],nP=[],nRP=[],sP=[];all.forEach(function(e){var hTP=e.tags.some(function(t){return isPlatform(getCat(t,reg))&&getDn(t,reg)==='Theater'});var vn=gV(e.tags,reg);if(hTP&&!vn)nV.push(e);if(!hTP&&vn)nS.push(e);if(vn){if(getCat(vn,reg)==='sub_venue'){var pr=gTP(e.tags,reg);if(pr!==null)sP.push({e:e,price:pr})}if(getCat(vn,reg)==='indie_venue'&&gTP(e.tags,reg)===null)nP.push(e)}var isR=e.tags.some(function(t){return getCat(t,reg)==='platform_rental'});if(isR&&gTP(e.tags,reg)===null)nRP.push(e)});return{unrated:all.filter(function(e){return e.rating===null}),nV:nV,nS:nS,nP:nP,nRP:nRP,sP:sP}}

var CTooltip=function(p){if(!p.active||!p.payload||!p.payload.length)return null;return <div className="bg-gray-800 border border-gray-600 rounded px-3 py-2 text-xs"><div className="text-gray-200 font-medium mb-1">{p.label}</div>{p.payload.filter(function(x){return x.value!=null}).map(function(x,i){return <div key={i} style={{color:x.color||'#34d399'}}>{x.name}: {typeof x.value==='number'?(Number.isInteger(x.value)?x.value:x.value.toFixed(2)):x.value}</div>})}</div>};
function SC(p){var yc=p.yoy?(p.yoy.charAt(0)==='+'?'text-emerald-500':p.yoy.charAt(0)==='-'?'text-red-400':'text-gray-600'):'';return <div className="bg-gray-900 rounded-xl p-3 text-center border border-gray-800"><div className="text-xl font-bold text-emerald-400">{p.value}</div><div className="text-xs text-gray-400 mt-1">{p.label}</div>{p.sub&&<div className="text-xs text-gray-600 mt-0.5">{p.sub}</div>}{p.yoy&&<div className={'text-xs mt-0.5 font-medium '+yc}>{p.yoy} YoY</div>}</div>}
function SrtB(p){return <button onClick={p.onToggle} className="text-xs bg-gray-800 text-gray-400 hover:text-gray-200 px-2 py-1 rounded">{p.val==='avg'?'Sort by Avg. Rating':'Sort by Count'}</button>}
function CTbl(p){var sorted=p.sortMode==='avg'?[].concat(p.data).sort(function(a,b){return(b.Avg||0)-(a.Avg||0)}):p.data;var mc=Math.max.apply(null,sorted.map(function(d){return d.Films}).concat([1]));return <div className="space-y-1">{sorted.map(function(d,i){var ac=p.sel===d.name;return <div key={i} onClick={function(){p.onSel(ac?null:d.name)}} title={d.tip||''} className={'flex items-center gap-2 cursor-pointer rounded px-1 py-0.5 '+(ac?'bg-gray-800 ring-1 ring-emerald-500':'hover:bg-gray-800/50')}><div className="w-28 text-xs text-gray-400 text-right truncate" title={d.name}>{d.name}</div><div className="flex-1 h-7 bg-gray-800 rounded overflow-hidden flex items-center"><div className="h-full rounded flex items-center px-2" style={{width:Math.max((d.Films/mc)*100,8)+'%',minWidth:32,backgroundColor:rC(d.Avg)}}><span className="text-xs font-bold" style={{color:'#111'}}>{d.Films}</span></div></div><div className="w-14 text-xs text-right font-mono" style={{color:rC(d.Avg)}}>{d.Avg>0?d.Avg.toFixed(1)+'★':'—'}</div></div>})}</div>}
function FilmList(p){if(!p.films||!p.films.length)return null;return <div className="bg-gray-900 rounded-xl p-4 border border-emerald-800 mt-3"><div className="flex justify-between items-center mb-2"><h3 className="text-sm font-semibold text-gray-300">{p.title} ({p.films.length})</h3><button onClick={p.onClose} className="text-xs text-gray-500 hover:text-gray-300 bg-gray-800 px-2 py-1 rounded">✕</button></div><div className="max-h-72 overflow-y-auto space-y-0.5">{p.films.map(function(f,i){return <div key={i} className="text-xs py-1 border-b border-gray-800 flex justify-between"><span className="text-gray-300 truncate mr-2">{f.name} <span className="text-gray-600">({f.year})</span>{f.rating!==null&&<span className="ml-1" style={{color:rC(f.rating)}}> {f.rating}★</span>}</span><span className="text-gray-500 whitespace-nowrap">{f.date}</span></div>})}</div></div>}
function DQPanel(p){var d=p.data;if(!d)return null;return <div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><h3 className="text-sm font-semibold text-gray-300 mb-3">🔍 Data Quality</h3><div className="space-y-2"><div className="text-xs text-gray-400">❓ {d.unrated.length} unrated</div>{d.nV.length>0&&<div className="text-xs text-yellow-400">⚠️ {d.nV.length} theater, no venue</div>}{d.nS.length>0&&<div className="text-xs text-yellow-400">⚠️ {d.nS.length} venue, no theater tag</div>}{d.nP.length>0&&<div className="text-xs text-red-400">🎟️ {d.nP.length} indie, no price</div>}{d.nRP.length>0&&<div className="text-xs text-red-400">📀 {d.nRP.length} rental, no price</div>}{d.sP.length>0&&<div className="text-xs text-blue-400">💎 {d.sP.length} sub premium</div>}{!d.nV.length&&!d.nS.length&&!d.nP.length&&!d.nRP.length&&<div className="text-xs text-emerald-400">✅ Clean</div>}</div></div>}

export default function Dashboard(){
  var[loading,sLoading]=useState(true);
  var[pd,sPd]=useState('');
  var[subs,sSubs]=useState(DSUBS);
  var[reg,sReg]=useState({});
  var[pwHash,sPwHash]=useState('');
  var[sI,sSI]=useState(false);
  var[csv,sCsv]=useState('');var[iR,sIR]=useState(null);
  var[tab,sTab]=useState('overview');var[yr,sYr]=useState('All');var[iRW,sIRW]=useState(true);
  var[sR,sSR]=useState(null);var[sP,sSP]=useState(null);var[sVe,sSVe]=useState(null);var[sCo,sSCo]=useState(null);var[sDe,sSDe]=useState(null);var[sTg,sSTg]=useState(null);
  var[sorts,sSorts]=useState({});var[sq,sSq]=useState('');var[selHM,sSelHM]=useState(null);
  var[dSrt,sDSrt]=useState({col:'date',asc:false});var[dSrch,sDSrch]=useState('');
  var[tagSearch,sTagSearch]=useState('');var[tagSel,sTagSel]=useState({});var[bulkCat,sBulkCat]=useState('');
  var[costEs,sCostEs]=useState(null);var[costYr,sCostYr]=useState('All');
  var[isAdmin,sIsAdmin]=useState(false);var[showPwModal,sShowPwModal]=useState(false);var[pwInput,sPwInput]=useState('');var[pwErr,sPwErr]=useState('');
  var[saving,sSaving]=useState(false);

  var ts=function(k){sSorts(function(p){var u={};u[k]=p[k]==='avg'?'vol':'avg';return Object.assign({},p,u)})};
  var cls=function(){sSR(null);sSP(null);sSVe(null);sSCo(null);sSDe(null);sSTg(null);sSelHM(null)};

  useEffect(function(){Promise.all([sb.from('pipe_data').select('data').eq('id',1).single(),sb.from('tag_registry').select('data').eq('id',1).single(),sb.from('subscriptions').select('data').eq('id',1).single(),sb.from('admin_password').select('hash').eq('id',1).single()]).then(function(r){if(r[0].data&&r[0].data.data)sPd(r[0].data.data);if(r[1].data&&r[1].data.data)sReg(r[1].data.data);if(r[2].data&&r[2].data.data&&Array.isArray(r[2].data.data))sSubs(r[2].data.data);if(r[3].data)sPwHash(r[3].data.hash||'');sLoading(false)}).catch(function(){sLoading(false)})},[]);

  var savePipe=useCallback(function(d){sSaving(true);sb.from('pipe_data').update({data:d,updated_at:new Date().toISOString()}).eq('id',1).then(function(){sSaving(false)}).catch(function(){sSaving(false)})},[]);
  var saveReg=useCallback(function(d){sb.from('tag_registry').update({data:d,updated_at:new Date().toISOString()}).eq('id',1).then(function(){})},[]);
  var saveSubs=useCallback(function(d){sb.from('subscriptions').update({data:d,updated_at:new Date().toISOString()}).eq('id',1).then(function(){})},[]);
  var savePw=useCallback(function(h){sb.from('admin_password').update({hash:h,updated_at:new Date().toISOString()}).eq('id',1).then(function(){})},[]);

  var doImport=useCallback(function(){if(!csv.trim())return;var r=csvToPipe(csv);sIR(r);if(r.pipe&&r.count>0){sPd(r.pipe);savePipe(r.pipe);if(!r.e.length){sSI(false);sYr('All')}}},[csv,savePipe]);
  var doClear=useCallback(function(){if(confirm('Clear all data?')){sPd('');sReg({});sSubs(DSUBS);savePipe('');saveReg({});saveSubs(DSUBS);sSI(false)}},[savePipe,saveReg,saveSubs]);
  var handlePwSubmit=useCallback(function(){if(!pwHash){if(pwInput.length<4){sPwErr('Min 4 chars');return}var h=simpleHash(pwInput);sPwHash(h);savePw(h);sIsAdmin(true);sShowPwModal(false);sPwInput('');sPwErr('')}else{if(simpleHash(pwInput)===pwHash){sIsAdmin(true);sShowPwModal(false);sPwInput('');sPwErr('')}else{sPwErr('Wrong password')}}},[pwInput,pwHash,savePw]);

  var doSetTag=function(t,cat){sReg(function(p){var n=Object.assign({},p);n[t]=Object.assign({},n[t]||{},{cat:cat||null});saveReg(n);return n})};
  var doSetDn=function(t,dn){sReg(function(p){var n=Object.assign({},p);n[t]=Object.assign({},n[t]||{},{dn:dn||''});saveReg(n);return n})};
  var doBulkTag=function(){if(!bulkCat)return;sReg(function(p){var n=Object.assign({},p);Object.keys(tagSel).forEach(function(t){if(tagSel[t])n[t]=Object.assign({},n[t]||{},{cat:bulkCat})});saveReg(n);return n});sTagSel({});sBulkCat('')};
  var doUpdateSubs=function(fn){sSubs(function(p){var n=fn(p);saveSubs(n);return n})};

  var all=useMemo(function(){return parsePipe(pd)},[pd]);
  var allTagCounts=useMemo(function(){var c={};all.forEach(function(e){e.tags.forEach(function(t){c[t]=(c[t]||0)+1})});return c},[all]);
  var fullReg=useMemo(function(){var r={};Object.keys(allTagCounts).forEach(function(t){r[t]=reg[t]||{cat:null,dn:''}});return r},[allTagCounts,reg]);
  var unclass=useMemo(function(){return Object.keys(fullReg).filter(function(t){return!fullReg[t].cat}).length},[fullReg]);
  var paidPlatTags=useMemo(function(){return Object.keys(fullReg).filter(function(t){return fullReg[t].cat==='platform_paid'}).sort()},[fullReg]);
  var yrs=useMemo(function(){return['All'].concat(Array.from(new Set(all.map(function(e){return e.date.slice(0,4)}))).sort())},[all]);
  var ef=useMemo(function(){var d=yr==='All'?all:all.filter(function(e){return e.date.indexOf(yr)===0});if(!iRW)d=d.filter(function(e){return!e.rewatch});return d},[all,yr,iRW]);
  var ea=useMemo(function(){return iRW?all:all.filter(function(e){return!e.rewatch})},[all,iRW]);
  var dq=useMemo(function(){return calcDQ(all,fullReg)},[all,fullReg]);
  var streaks=useMemo(function(){return calcStreaks(ef)},[ef]);
  var wrapped=useMemo(function(){return calcWrapped(all,fullReg)},[all,fullReg]);
  var isT=useCallback(function(e){return gP(e.tags,fullReg)==='Theater'||gV(e.tags,fullReg)!==null},[fullReg]);
  var stats=useMemo(function(){var f=ef,rt=f.filter(function(e){return e.rating!==null}),av=rt.length?rt.reduce(function(s,e){return s+e.rating},0)/rt.length:0;return{total:f.length,avg:av.toFixed(2),th:f.filter(isT).length,rw:f.filter(function(e){return e.rewatch}).length,fo:f.filter(function(e){return e.tags.indexOf('foreign')!==-1}).length,fr:f.filter(function(e){return gC(e.tags,fullReg).length>0}).length}},[ef,fullReg,isT]);
  var yoy=useMemo(function(){if(yr==='All')return null;var py=String(parseInt(yr)-1),pv=all.filter(function(e){return e.date.indexOf(py)===0});if(!pv.length)return null;if(!iRW)pv=pv.filter(function(e){return!e.rewatch});var pN=pv.length,cN=ef.length;if(!pN||!cN)return null;var pp=function(cf,pf){return(cf/cN*100)-(pf/pN*100)};var pR=pv.filter(function(e){return e.rating!==null}),cR=ef.filter(function(e){return e.rating!==null});return{films:cN-pN,avg:(pR.length&&cR.length)?(cR.reduce(function(s,e){return s+e.rating},0)/cR.length)-(pR.reduce(function(s,e){return s+e.rating},0)/pR.length):null,th:pp(ef.filter(isT).length,pv.filter(isT).length),rw:iRW?pp(ef.filter(function(e){return e.rewatch}).length,pv.filter(function(e){return e.rewatch}).length):null,fo:pp(ef.filter(function(e){return e.tags.indexOf('foreign')!==-1}).length,pv.filter(function(e){return e.tags.indexOf('foreign')!==-1}).length),fr:pp(ef.filter(function(e){return gC(e.tags,fullReg).length>0}).length,pv.filter(function(e){return gC(e.tags,fullReg).length>0}).length)}},[yr,ef,all,iRW,fullReg,isT]);
  var searchRes=useMemo(function(){if(!sq||sq.length<2)return[];var q=sq.toLowerCase();return all.filter(function(e){return e.name.toLowerCase().indexOf(q)!==-1}).slice(0,12)},[all,sq]);
  var binge=useMemo(function(){var dt=Array.from(new Set(ef.map(function(e){return e.date}))).sort();if(dt.length<2)return{streak:1,range:dt[0]||'N/A'};var ms=1,cs=1,mi=0,ci=0;for(var i=1;i<dt.length;i++){var d=Math.round((new Date(dt[i])-new Date(dt[i-1]))/864e5);if(d===1){cs++;if(cs>ms){ms=cs;mi=ci}}else{cs=1;ci=i}}var sd=dt.slice(mi,mi+ms),s0=sd[0].split('-').map(Number),sL=sd[sd.length-1].split('-').map(Number);var r;if(ms===1)r=MF[s0[1]-1]+' '+s0[2]+', '+s0[0];else if(s0[0]===sL[0]&&s0[1]===sL[1])r=MF[s0[1]-1]+' '+s0[2]+'–'+sL[2]+', '+s0[0];else r=MS[s0[1]-1]+' '+s0[2]+' – '+MS[sL[1]-1]+' '+sL[2]+', '+s0[0];return{streak:ms,range:r}},[ef]);
  var busiest=useMemo(function(){var c={};ef.forEach(function(e){c[e.date]=(c[e.date]||0)+1});var en=Object.entries(c).sort(function(a,b){return b[1]-a[1]});if(!en.length)return{count:0,fmt:'N/A',films:[]};var d=en[0][0],n=en[0][1],p=d.split('-').map(Number);return{count:n,fmt:MF[p[1]-1]+' '+p[2]+', '+p[0],films:ef.filter(function(e){return e.date===d}).map(function(e){return e.name})}},[ef]);
  var bestMo=useMemo(function(){var c={};ef.forEach(function(e){var m=e.date.slice(0,7);c[m]=(c[m]||0)+1});return Object.entries(c).sort(function(a,b){return b[1]-a[1]}).slice(0,1).map(function(x){return{label:fmtM(x[0]),count:x[1]}})},[ef]);
  var hmData=useMemo(function(){var yy=Array.from(new Set(ea.map(function(e){return e.date.slice(0,4)}))).sort(),g={};yy.forEach(function(y){g[y]=Array(12).fill(0)});ea.forEach(function(e){var y=e.date.slice(0,4),m=parseInt(e.date.slice(5,7))-1;if(g[y])g[y][m]++});return{years:yy,grid:g,max:Math.max.apply(null,Object.values(g).map(function(a){return Math.max.apply(null,a)}).concat([1]))}},[ea]);
  var hmFilms=useMemo(function(){if(!selHM)return[];return ea.filter(function(e){return e.date.slice(0,4)===selHM.yr&&parseInt(e.date.slice(5,7))===selHM.mo+1})},[ea,selHM]);
  var cumData=useMemo(function(){var yy=Array.from(new Set(ea.map(function(e){return parseInt(e.date.slice(0,4))}))).sort(function(a,b){return a-b}),last={},first={};ea.forEach(function(e){var y=parseInt(e.date.slice(0,4)),m=parseInt(e.date.slice(5,7));last[y]=Math.max(last[y]||0,m);first[y]=Math.min(first[y]||13,m)});var rows=[];for(var m=1;m<=12;m++){var row={month:MS[m-1]};yy.forEach(function(y){row[y]=m<(first[y]||1)||m>(last[y]||12)?null:ea.filter(function(e){return parseInt(e.date.slice(0,4))===y&&parseInt(e.date.slice(5,7))<=m}).length});rows.push(row)}return{data:rows,years:yy}},[ea]);
  var rDist=useMemo(function(){var c={};for(var r=0.5;r<=5;r+=0.5)c[r]=0;ef.forEach(function(e){if(e.rating!==null)c[e.rating]=(c[e.rating]||0)+1});return Object.entries(c).sort(function(a,b){return parseFloat(a[0])-parseFloat(b[0])}).map(function(x){return{rating:x[0],count:x[1]}})},[ef]);
  var selFilms=useMemo(function(){return sR===null?[]:ef.filter(function(e){return e.rating===sR})},[ef,sR]);
  var platD=useMemo(function(){return agg(ef,function(e){return gP(e.tags,fullReg)}).sort(function(a,b){return b.Films-a.Films})},[ef,fullReg]);
  var platF=useMemo(function(){return sP?ef.filter(function(e){return gP(e.tags,fullReg)===sP}):[]},[ef,sP,fullReg]);
  var venD=useMemo(function(){var v={};ef.forEach(function(e){var vn=gV(e.tags,fullReg);if(!vn)return;var dn=getDn(vn,fullReg);if(!v[dn])v[dn]={c:0,s:0,r:0};v[dn].c++;if(e.rating!==null){v[dn].s+=e.rating;v[dn].r++}});return Object.keys(v).map(function(n){var d=v[n];return{name:n,Films:d.c,Avg:d.r?parseFloat((d.s/d.r).toFixed(2)):0}}).sort(function(a,b){return b.Films-a.Films})},[ef,fullReg]);
  var venF=useMemo(function(){return sVe?ef.filter(function(e){var vn=gV(e.tags,fullReg);return vn&&getDn(vn,fullReg)===sVe}):[]},[ef,sVe,fullReg]);
  var compD=useMemo(function(){var c={},ft={};ef.forEach(function(e){gC(e.tags,fullReg).forEach(function(n){if(!c[n])c[n]={c:0,s:0,r:0};c[n].c++;if(e.rating!==null){c[n].s+=e.rating;c[n].r++}if(!ft[n])ft[n]=[];ft[n].push(e)})});return Object.keys(c).map(function(n){var v=c[n],t3=(ft[n]||[]).filter(function(e){return e.rating!==null}).sort(function(a,b){return b.rating-a.rating}).slice(0,3).map(function(e){return e.name+' ('+e.rating+'★)'}).join(', ');return{name:n,Films:v.c,Avg:v.r?parseFloat((v.s/v.r).toFixed(2)):0,tip:t3?'Top: '+t3:''}}).sort(function(a,b){return b.Films-a.Films})},[ef,fullReg]);
  var compF=useMemo(function(){return sCo?ef.filter(function(e){return gC(e.tags,fullReg).indexOf(sCo)!==-1}):[]},[ef,sCo,fullReg]);
  var solo=useMemo(function(){var s=ef.filter(function(e){return gC(e.tags,fullReg).length>0}).length;return{solo:ef.length-s,social:s}},[ef,fullReg]);
  var decD=useMemo(function(){return agg(ef,function(e){return Math.floor(e.year/10)*10+'s'}).sort(function(a,b){return a.name<b.name?-1:1})},[ef]);
  var decF=useMemo(function(){return sDe?ef.filter(function(e){return Math.floor(e.year/10)*10===parseInt(sDe)}):[]},[ef,sDe]);
  var tasteTags=useMemo(function(){return Object.keys(fullReg).filter(function(t){return fullReg[t].cat==='taste'})},[fullReg]);
  var tagD=useMemo(function(){return tasteTags.map(function(t){var m=ef.filter(function(e){return e.tags.indexOf(t)!==-1}),r=m.filter(function(e){return e.rating!==null});return{name:getDn(t,fullReg),tag:t,Films:m.length,Avg:r.length?parseFloat((r.reduce(function(s,e){return s+e.rating},0)/r.length).toFixed(2)):0}}).sort(function(a,b){return b.Films-a.Films})},[ef,tasteTags,fullReg]);
  var tagF=useMemo(function(){if(!sTg)return[];var entry=tagD.find(function(d){return d.name===sTg});return entry?ef.filter(function(e){return e.tags.indexOf(entry.tag)!==-1}):[]},[ef,sTg,tagD]);
  var diaryData=useMemo(function(){var d=ef.filter(function(e){return!dSrch||e.name.toLowerCase().indexOf(dSrch.toLowerCase())!==-1});return[].concat(d).sort(function(a,b){var c=dSrt.col,m=dSrt.asc?1:-1;if(c==='date')return(a.date<b.date?-1:1)*m;if(c==='name')return a.name.toLowerCase()<b.name.toLowerCase()?-m:m;if(c==='year')return(a.year-b.year)*m;if(c==='rating')return((a.rating||0)-(b.rating||0))*m;return 0})},[ef,dSrt,dSrch]);
  var tagAllSorted=useMemo(function(){return Object.keys(fullReg).sort(function(a,b){return(allTagCounts[b]||0)-(allTagCounts[a]||0)})},[fullReg,allTagCounts]);
  var tagFiltered=useMemo(function(){return tagAllSorted.filter(function(t){return!tagSearch||t.indexOf(tagSearch.toLowerCase())!==-1})},[tagAllSorted,tagSearch]);
  var tagSelCount=useMemo(function(){return Object.keys(tagSel).filter(function(k){return tagSel[k]}).length},[tagSel]);
  var tagGrouped=useMemo(function(){var g={_un:[]};CATS.forEach(function(c){g[c]=[]});tagFiltered.forEach(function(t){var c=fullReg[t]&&fullReg[t].cat;if(c&&g[c])g[c].push(t);else g._un.push(t)});return g},[tagFiltered,fullReg]);
  var costYrs=useMemo(function(){return['All'].concat(Array.from(new Set(all.map(function(e){return e.date.slice(0,4)}))).sort())},[all]);
  var costData=useMemo(function(){return Array.from(new Set(all.map(function(e){return e.date.slice(0,4)}))).sort().map(function(y){var films=all.filter(function(e){return e.date.indexOf(y)===0});var st=0,sbk=[];subs.forEach(function(sub){sub.periods.forEach(function(pr){if(!pr.from||!pr.price)return;var pTo=pr.to||((parseInt(y)+1)+'-01'),yS=y+'-01',yE=y+'-12',eF=pr.from>yS?pr.from:yS,eT=pTo<yE?pTo:yE;if(eF>eT)return;var mo=mBt(eF,eT),co=mo*pr.price;st+=co;sbk.push({name:sub.name,mo:mo,price:pr.price,cost:co})})});var tt=0,tc=0,rt=0,rc=0;films.forEach(function(e){var isTh=gV(e.tags,fullReg)!==null||e.tags.some(function(t){return isPlatform(getCat(t,fullReg))&&getDn(t,fullReg)==='Theater'});var isRe=e.tags.some(function(t){return getCat(t,fullReg)==='platform_rental'});if(isTh){var p=gTP(e.tags,fullReg);if(p!==null){tt+=p;tc++}}if(isRe){var p2=gTP(e.tags,fullReg);if(p2!==null){rt+=p2;rc++}}});
      // Per-platform breakdown
      var platRows=[];subs.forEach(function(sub){var subCost=0;sub.periods.forEach(function(pr){if(!pr.from||!pr.price)return;var pTo=pr.to||((parseInt(y)+1)+'-01'),yS=y+'-01',yE=y+'-12',eF=pr.from>yS?pr.from:yS,eT=pTo<yE?pTo:yE;if(eF>eT)return;subCost+=mBt(eF,eT)*pr.price});var subFilmCount=films.filter(function(e){return e.tags.some(function(t){return sub.platforms.indexOf(t)!==-1})}).length;var cpf=subFilmCount?subCost/subFilmCount:0;sub.platforms.forEach(function(pt){var cnt=films.filter(function(e){return e.tags.indexOf(pt)!==-1}).length;if(cnt>0)platRows.push({plat:getDn(pt,fullReg),films:cnt,sub:sub.name,cost:cpf*cnt,cpf:cpf})})});
      var rentalF=films.filter(function(e){return e.tags.some(function(t){return getCat(t,fullReg)==='platform_rental'})});var rentalC=0;rentalF.forEach(function(e){var p=gTP(e.tags,fullReg);if(p!==null)rentalC+=p});if(rentalF.length)platRows.push({plat:'Rental',films:rentalF.length,sub:'Per use',cost:rentalC,cpf:rentalF.length?rentalC/rentalF.length:0});
      var indieF=films.filter(function(e){var vn=gV(e.tags,fullReg);return vn&&getCat(vn,fullReg)==='indie_venue'});var indieC=0;indieF.forEach(function(e){var p=gTP(e.tags,fullReg);if(p!==null)indieC+=p});if(indieF.length)platRows.push({plat:'Indie Theaters',films:indieF.length,sub:'Per ticket',cost:indieC,cpf:indieF.length?indieC/indieF.length:0});
      var subVF=films.filter(function(e){var vn=gV(e.tags,fullReg);return vn&&getCat(vn,fullReg)==='sub_venue'});var thSub=subs.find(function(s){return s.platforms.indexOf('_theater_sub')!==-1});var thSubCost=0;if(thSub)thSub.periods.forEach(function(pr){if(!pr.from||!pr.price)return;var pTo=pr.to||((parseInt(y)+1)+'-01'),yS=y+'-01',yE=y+'-12',eF=pr.from>yS?pr.from:yS,eT=pTo<yE?pTo:yE;if(eF>eT)return;thSubCost+=mBt(eF,eT)*pr.price});if(subVF.length)platRows.push({plat:'Sub Theaters',films:subVF.length,sub:thSub?thSub.name:'Pass',cost:thSubCost,cpf:subVF.length?thSubCost/subVF.length:0});
      var tot=st+tt+rt;return{yr:y,films:films.length,st:st,sbk:sbk,tt:tt,tc:tc,rt:rt,rc:rc,tot:tot,pf:films.length?tot/films.length:0,platRows:platRows}})},[all,subs,fullReg]);
  var costDataFilt=useMemo(function(){return costYr==='All'?costData:costData.filter(function(d){return d.yr===costYr})},[costData,costYr]);

  var renderTagRow=function(t,showCheck){var e=fullReg[t]||{};return <div key={t} className="flex items-center gap-2 py-1 border-b border-gray-800/50">{showCheck&&<input type="checkbox" checked={!!tagSel[t]} onChange={function(){sTagSel(function(p){var n=Object.assign({},p);n[t]=!n[t];return n})}} className="accent-emerald-500"/>}<div className="flex-1 text-xs text-gray-300 truncate min-w-0" title={t}>{t}</div><div className="text-xs text-gray-600 w-8 text-right shrink-0">{allTagCounts[t]||0}</div>{isAdmin?<select className="bg-gray-800 border border-gray-700 rounded text-xs text-gray-300 px-1 py-0.5 w-28 shrink-0" value={e.cat||''} onChange={function(ev){doSetTag(t,ev.target.value)}}><option value="">—</option>{CATS.map(function(c){return <option key={c} value={c}>{CI[c].l}</option>})}</select>:<div className={'text-xs w-28 shrink-0 text-right '+(e.cat?CI[e.cat].c:'text-gray-600')}>{e.cat?CI[e.cat].l:'—'}</div>}{isAdmin?<input className="bg-gray-800 border border-gray-700 rounded text-xs text-gray-300 px-1 py-0.5 w-28 shrink-0" placeholder="Display name" value={e.dn||''} onChange={function(ev){doSetDn(t,ev.target.value)}}/>:<div className="text-xs text-gray-500 w-28 shrink-0 text-right truncate">{e.dn||''}</div>}</div>};

  var TABS_ALL=[{id:'overview',l:'📊 Overview'},{id:'ratings',l:'⭐ Ratings'},{id:'where',l:'📍 Where'},{id:'who',l:'👥 Who'},{id:'taste',l:'🎭 Taste'},{id:'diary',l:'📖 Diary'},{id:'costs',l:'💰 Costs'},{id:'tags',l:'🏷️ Tags'}];
  var TABS=isAdmin?TABS_ALL:TABS_ALL.filter(function(t){return t.id!=='tags'});

  var pwModal=showPwModal?<div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50" onClick={function(){sShowPwModal(false);sPwInput('');sPwErr('')}}><div className="bg-gray-900 rounded-xl p-6 border border-gray-700 w-80" onClick={function(e){e.stopPropagation()}}><h3 className="text-sm font-semibold text-gray-300 mb-3">{pwHash?'🔐 Enter Password':'🔐 Set Admin Password'}</h3><input type="password" className="w-full bg-gray-800 border border-gray-700 rounded px-3 py-2 text-sm text-gray-300 mb-2 focus:outline-none focus:border-emerald-500" value={pwInput} onChange={function(e){sPwInput(e.target.value);sPwErr('')}} onKeyDown={function(e){if(e.key==='Enter')handlePwSubmit()}}/>{pwErr&&<div className="text-xs text-red-400 mb-2">{pwErr}</div>}<div className="flex gap-2"><button onClick={handlePwSubmit} className="bg-emerald-600 text-white px-4 py-1.5 rounded text-sm font-medium flex-1">Enter</button><button onClick={function(){sShowPwModal(false);sPwInput('');sPwErr('')}} className="bg-gray-800 text-gray-400 px-4 py-1.5 rounded text-sm flex-1">Cancel</button></div></div></div>:null;

  var costSummary=<div className="space-y-4">
    <div className="flex gap-1 flex-wrap">{costYrs.map(function(y){return <button key={y} onClick={function(){sCostYr(y)}} className={'px-2.5 py-1 rounded text-xs font-medium '+(costYr===y?'bg-emerald-600 text-white':'bg-gray-800 text-gray-400')}>{y}</button>})}</div>
    {costDataFilt.map(function(d){return <div key={d.yr} className="space-y-3 mb-6">
      <div className="flex items-center gap-2"><h4 className="text-sm font-bold text-emerald-400">{d.yr}</h4><span className="text-xs text-gray-600">{d.films} films</span></div>
      <div className="grid grid-cols-2 md:grid-cols-5 gap-2"><div className="bg-gray-800 rounded p-2 text-center"><div className="text-sm font-bold text-emerald-400">€{d.st.toFixed(0)}</div><div className="text-xs text-gray-500">Subs</div></div><div className="bg-gray-800 rounded p-2 text-center"><div className="text-sm font-bold text-amber-400">€{d.tt.toFixed(2)}</div><div className="text-xs text-gray-500">Tickets ({d.tc})</div></div><div className="bg-gray-800 rounded p-2 text-center"><div className="text-sm font-bold text-blue-400">€{d.rt.toFixed(2)}</div><div className="text-xs text-gray-500">Rentals ({d.rc})</div></div><div className="bg-gray-800 rounded p-2 text-center"><div className="text-sm font-bold text-white">€{d.tot.toFixed(2)}</div><div className="text-xs text-gray-500">Total</div></div><div className="bg-gray-800 rounded p-2 text-center"><div className="text-sm font-bold text-pink-400">€{d.pf.toFixed(2)}</div><div className="text-xs text-gray-500">/Film</div></div></div>
      {d.sbk.length>0&&<div className="text-xs text-gray-500 ml-2">{d.sbk.map(function(s,i){return <div key={i}>{s.name}: {s.mo}mo × €{s.price} = <span className="text-gray-300">€{s.cost.toFixed(0)}</span></div>})}</div>}
      {d.platRows.length>0&&<div className="bg-gray-900 rounded-xl p-3 border border-gray-800"><h4 className="text-xs font-semibold text-gray-400 mb-2">Per Platform</h4><table className="w-full text-xs"><thead><tr className="text-gray-500 border-b border-gray-800"><th className="text-left py-1">Platform</th><th className="text-right py-1">Films</th><th className="text-right py-1">Via</th><th className="text-right py-1">Cost</th><th className="text-right py-1">/Film</th></tr></thead><tbody>{d.platRows.map(function(r,i){return <tr key={i} className="border-b border-gray-800/50"><td className="py-1 text-gray-300">{r.plat}</td><td className="py-1 text-right text-gray-400">{r.films}</td><td className="py-1 text-right text-gray-500">{r.sub}</td><td className="py-1 text-right text-gray-300">€{r.cost.toFixed(2)}</td><td className="py-1 text-right text-pink-400">€{r.cpf.toFixed(2)}</td></tr>})}</tbody></table></div>}
      <div className="border-b border-gray-800"/>
    </div>})}
  </div>;

  if(loading)return <div className="bg-gray-950 text-gray-100 min-h-screen flex items-center justify-center"><div className="text-center"><div className="text-2xl mb-2">🎬</div><div className="text-gray-400 text-sm">Loading...</div></div></div>;

  if(sI||(isAdmin&&!all.length))return(<div className="bg-gray-950 text-gray-100 min-h-screen p-4 md:p-8">{pwModal}<div className="max-w-4xl mx-auto">
    <div className="flex justify-between items-center mb-4"><h1 className="text-2xl font-bold text-emerald-400">📥 Import CSV</h1>{all.length>0&&<button onClick={function(){sSI(false)}} className="text-xs bg-gray-800 text-gray-400 px-3 py-1.5 rounded">← Back</button>}</div>
    <textarea className="w-full h-56 bg-gray-900 border border-gray-700 rounded-lg p-3 text-xs text-gray-300 font-mono focus:outline-none focus:border-emerald-500 resize-y mb-3" value={csv} onChange={function(e){sCsv(e.target.value);sIR(null)}}/>
    <button onClick={doImport} disabled={!csv.trim()} className="bg-emerald-600 hover:bg-emerald-500 disabled:bg-gray-700 disabled:text-gray-500 text-white px-5 py-2 rounded-lg text-sm font-medium">🔄 Parse & Save</button>
    {iR&&<div className="mt-4 space-y-3">{iR.count>0&&<div className="bg-emerald-950 border border-emerald-800 rounded-lg p-3 text-sm text-emerald-400">✅ {iR.count} entries</div>}{iR.e.length>0&&<div className="bg-red-950 border border-red-800 rounded-lg p-4">{iR.e.map(function(e,i){return <div key={i} className="text-xs text-red-300">{e}</div>})}</div>}{iR.count>0&&!iR.e.length&&<button onClick={function(){sSI(false)}} className="bg-emerald-600 text-white px-5 py-2 rounded-lg text-sm font-medium">→ Continue</button>}</div>}
  </div></div>);

  if(unclass>0&&isAdmin)return(<div className="bg-gray-950 text-gray-100 min-h-screen p-4 md:p-8">{pwModal}<div className="max-w-5xl mx-auto">
    <h1 className="text-2xl font-bold text-emerald-400 mb-1">🏷️ Classify Tags</h1>
    <p className="text-gray-500 text-sm mb-4"><span className="text-red-400 font-medium">{unclass} unsorted.</span></p>
    <div className="flex flex-wrap gap-2 mb-4 items-center">
      <input className="bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-300 focus:outline-none focus:border-emerald-500 flex-1 min-w-48" placeholder="🔍 Filter..." value={tagSearch} onChange={function(e){sTagSearch(e.target.value)}}/>
      {tagSelCount>0&&<div className="flex items-center gap-2 bg-gray-900 rounded-lg px-3 py-2 border border-gray-700"><span className="text-xs text-gray-300">{tagSelCount} sel</span><select className="bg-gray-800 border border-gray-700 rounded text-xs text-gray-300 px-1 py-0.5" value={bulkCat} onChange={function(e){sBulkCat(e.target.value)}}><option value="">Assign...</option>{CATS.map(function(c){return <option key={c} value={c}>{CI[c].l}</option>})}</select><button onClick={doBulkTag} disabled={!bulkCat} className="text-xs bg-emerald-700 disabled:bg-gray-700 text-white px-2 py-0.5 rounded">Apply</button><button onClick={function(){sTagSel({})}} className="text-xs text-gray-500">Clear</button></div>}
      <button onClick={function(){var n={};tagFiltered.forEach(function(t){n[t]=true});sTagSel(n)}} className="text-xs bg-gray-800 text-gray-400 px-2 py-1 rounded">Select visible</button>
    </div>
    {tagGrouped._un.length>0&&<div className="bg-red-950 rounded-xl p-4 border border-red-800 mb-4"><h3 className="text-sm font-semibold text-red-400 mb-2">⚠️ Unsorted ({tagGrouped._un.length})</h3><div className="space-y-0.5">{tagGrouped._un.map(function(t){return renderTagRow(t,true)})}</div></div>}
    {CATS.map(function(cat){var tags=tagGrouped[cat];if(!tags||!tags.length)return null;return <div key={cat} className={'rounded-xl p-4 border mb-3 '+CI[cat].bg}><h3 className={'text-sm font-semibold mb-2 '+CI[cat].c}>{CI[cat].l} ({tags.length})</h3><div className="space-y-0.5 max-h-64 overflow-y-auto">{tags.map(function(t){return renderTagRow(t,true)})}</div></div>})}
  </div></div>);

  if(!all.length&&!isAdmin)return(<div className="bg-gray-950 text-gray-100 min-h-screen flex items-center justify-center">{pwModal}<div className="text-center"><div className="text-2xl mb-2">🎬</div><div className="text-gray-400 text-sm mb-4">No data yet.</div><button onClick={function(){sShowPwModal(true)}} className="bg-gray-800 text-gray-400 px-4 py-2 rounded-lg text-sm">🔐 Admin</button></div></div>);

  var tagGroupedDash={};CATS.forEach(function(c){tagGroupedDash[c]=[]});tagAllSorted.filter(function(t){return!tagSearch||t.indexOf(tagSearch.toLowerCase())!==-1}).forEach(function(t){var c=fullReg[t]&&fullReg[t].cat;if(c&&tagGroupedDash[c])tagGroupedDash[c].push(t)});

  return(<div className="bg-gray-950 text-gray-100 min-h-screen p-3 md:p-6">{pwModal}<div className="max-w-5xl mx-auto">
    <div className="flex justify-between items-start mb-3"><div><h1 className="text-2xl font-bold text-emerald-400 mb-1">🎬 Babylonian's Letterboxd Analytics</h1></div><div className="flex gap-2 items-center">{isAdmin&&<span className="text-xs text-emerald-500">Admin</span>}{isAdmin?<button onClick={function(){sIsAdmin(false)}} className="bg-gray-800 text-gray-400 px-3 py-1.5 rounded-lg text-xs">🔓 Lock</button>:<button onClick={function(){sShowPwModal(true)}} className="bg-gray-800 text-gray-500 px-3 py-1.5 rounded-lg text-xs">🔐</button>}{isAdmin&&<button onClick={function(){sSI(true)}} className="bg-gray-800 text-gray-300 px-3 py-1.5 rounded-lg text-xs">📥</button>}{isAdmin&&<button onClick={doClear} className="bg-gray-800 text-gray-500 hover:text-red-300 px-3 py-1.5 rounded-lg text-xs">🗑️</button>}</div></div>
    {unclass>0&&!isAdmin&&<div className="bg-yellow-950 border border-yellow-800 rounded-lg p-3 mb-3 text-xs text-yellow-400">⚠️ {unclass} tags unclassified.</div>}
    <div className="relative mb-3"><input className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-300 focus:outline-none focus:border-emerald-500" placeholder="🔍 Search..." value={sq} onChange={function(e){sSq(e.target.value)}}/>{searchRes.length>0&&<div className="absolute z-50 w-full bg-gray-900 border border-gray-700 rounded-lg mt-1 max-h-72 overflow-y-auto shadow-xl">{searchRes.map(function(f,i){return <div key={i} className="px-3 py-2 hover:bg-gray-800 border-b border-gray-800 flex justify-between text-sm"><span className="text-gray-200 truncate mr-2">{f.name} <span className="text-gray-500">({f.year})</span>{f.rating!==null&&<span style={{color:rC(f.rating)}}> {f.rating}★</span>}</span><span className="text-xs text-gray-500">{f.date}</span></div>})}</div>}</div>
    <div className="flex gap-1 mb-4 flex-wrap">{TABS.map(function(t){return <button key={t.id} onClick={function(){sTab(t.id);cls();sSq('')}} className={'px-2.5 py-1.5 rounded-lg text-xs font-medium '+(tab===t.id?'bg-emerald-600 text-white':'bg-gray-800 text-gray-400 hover:text-gray-200')}>{t.l}</button>})}</div>
    {['overview','ratings','where','who','taste','diary'].indexOf(tab)!==-1&&<div className="flex flex-wrap items-center gap-3 mb-4"><div className="flex gap-1 flex-wrap">{yrs.map(function(y){return <button key={y} onClick={function(){sYr(y);cls()}} className={'px-2.5 py-1 rounded text-xs font-medium '+(yr===y?'bg-emerald-600 text-white':'bg-gray-800 text-gray-400')}>{y}</button>})}</div><button onClick={function(){sIRW(function(v){return!v});cls()}} className={'px-2.5 py-1 rounded text-xs font-medium '+(iRW?'bg-gray-800 text-gray-400':'bg-amber-600 text-white')}>{iRW?'Incl. Rewatches':'Excl. Rewatches'}</button></div>}

    {tab==='overview'&&<div className="space-y-4">
      <div className="grid grid-cols-3 md:grid-cols-6 gap-2"><SC label="Films" value={stats.total} yoy={yoy&&fY(yoy.films,'abs')}/><SC label="Avg ⭐" value={stats.avg} yoy={yoy&&fY(yoy.avg,'r')}/><SC label="In Theaters" value={stats.th} yoy={yoy&&fY(yoy.th,'pp')}/><SC label="Rewatches" value={stats.rw} yoy={yoy&&yoy.rw!=null?fY(yoy.rw,'pp'):null}/><SC label="Foreign" value={stats.fo} yoy={yoy&&fY(yoy.fo,'pp')}/><SC label="With Friends" value={stats.fr} yoy={yoy&&fY(yoy.fr,'pp')}/></div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
        <div className="bg-gray-900 rounded-xl p-3 border border-gray-800"><div className="text-xs text-gray-500 mb-1">Longest Binge</div><div className="text-lg font-bold text-emerald-400">{binge.streak} days</div><div className="text-xs text-gray-500">{binge.range}</div></div>
        <div className="bg-gray-900 rounded-xl p-3 border border-gray-800"><div className="text-xs text-gray-500 mb-1">Current Streak</div><div className="text-lg font-bold text-emerald-400">{streaks.week} weeks</div><div className="text-xs text-gray-500">{streaks.wr}</div></div>
        <div className="bg-gray-900 rounded-xl p-3 border border-gray-800" title={busiest.films.join(', ')}><div className="text-xs text-gray-500 mb-1">Most Watched in a Day</div><div className="text-lg font-bold text-emerald-400">{busiest.count} films</div><div className="text-xs text-gray-500">{busiest.fmt}</div></div>
        <div className="bg-gray-900 rounded-xl p-3 border border-gray-800"><div className="text-xs text-gray-500 mb-1">Busiest Month</div><div className="text-lg font-bold text-emerald-400">{bestMo.length?bestMo[0].count:0} films</div><div className="text-xs text-gray-500">{bestMo.length?bestMo[0].label:''}</div></div>
      </div>
      <div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><h3 className="text-sm font-semibold text-gray-300 mb-3">Heatmap <span className="text-xs text-gray-600">(click)</span></h3><div className="overflow-x-auto"><div style={{minWidth:500}}><div className="flex items-center mb-1"><div className="w-12"/>{MS.map(function(m,i){return <div key={i} className="flex-1 text-center text-xs text-gray-600">{m}</div>})}</div>{hmData.years.map(function(y){return <div key={y} className="flex items-center gap-0.5 mb-0.5" style={yr===y?{outline:'1px solid #34d399',borderRadius:4}:{}}><div className="w-12 text-xs text-gray-500 text-right pr-2">{y}</div>{hmData.grid[y].map(function(c,m){var it=c===0?0:0.15+(c/hmData.max)*0.85,iS=selHM&&selHM.yr===y&&selHM.mo===m;return <div key={m} onClick={function(){sSelHM(c>0?(iS?null:{yr:y,mo:m}):null)}} className={'flex-1 flex items-center justify-center rounded-sm '+(c>0?'cursor-pointer':'')} style={{height:28,backgroundColor:c===0?'#111827':'rgba(52,211,153,'+it+')',color:c>0?(it>0.5?'#064e3b':'#d1d5db'):'transparent',outline:iS?'2px solid #fff':'none'}}><span className="text-xs font-medium">{c>0?c:''}</span></div>})}</div>})}</div></div>{selHM&&<FilmList title={MF[selHM.mo]+' '+selHM.yr} films={hmFilms} onClose={function(){sSelHM(null)}}/>}</div>
      <div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><h3 className="text-sm font-semibold text-gray-300 mb-3">Cumulative Films Per Year</h3><ResponsiveContainer width="100%" height={260}><LineChart data={cumData.data}><CartesianGrid strokeDasharray="3 3" stroke="#1f2937"/><XAxis dataKey="month" tick={{fill:'#6b7280',fontSize:10}}/><YAxis tick={{fill:'#6b7280',fontSize:10}}/><Tooltip content={CTooltip}/>{cumData.years.map(function(y,i){return <Line key={y} type="monotone" dataKey={String(y)} stroke={YC[y]||CLR[i%CLR.length]} strokeWidth={yr!=='All'&&yr===String(y)?3:1.5} dot={false} connectNulls={false} opacity={yr!=='All'&&yr!==String(y)?0.25:1}/>})}</LineChart></ResponsiveContainer><div className="flex gap-3 flex-wrap mt-2">{cumData.years.map(function(y){return <div key={y} className="flex items-center gap-1"><div className="w-3 h-0.5 rounded" style={{backgroundColor:YC[y]||'#999'}}/><span className="text-xs text-gray-500">{y}</span></div>})}</div></div>
      <div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><h3 className="text-sm font-semibold text-gray-300 mb-3">Year Wrapped</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{wrapped.filter(function(w){return yr==='All'||w.yr===yr}).map(function(w){return <div key={w.yr} className="bg-gray-800 rounded-lg p-4"><div className="text-sm font-bold mb-3" style={{color:YC[w.yr]||'#34d399'}}>{w.yr}</div><div className="grid grid-cols-2 gap-2 mb-3"><div className="text-center"><div className="text-xl font-bold text-emerald-400">{w.total}</div><div className="text-xs text-gray-500">Films Watched</div></div><div className="text-center"><div className="text-xl font-bold text-yellow-400">⭐ {w.avg.toFixed(2)}</div><div className="text-xs text-gray-500">Avg. Rating</div></div></div><div className="space-y-1 text-xs">{w.topC&&<div className="text-gray-300"><span className="text-gray-500">Best Friend:</span> {w.topC} ({w.topCC})</div>}{w.topMo&&<div className="text-gray-300"><span className="text-gray-500">Busiest Month:</span> {w.topMo} ({w.topMC})</div>}<div className="text-gray-300"><span className="text-gray-500">Theater:</span> {w.thPct}%</div></div></div>})}</div></div>
    </div>}

    {tab==='ratings'&&<div className="space-y-4"><div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><div className="flex justify-between items-center mb-3"><h3 className="text-sm font-semibold text-gray-300">Rating Distribution</h3><div className="text-sm font-bold text-yellow-400">Avg: {stats.avg} ⭐</div></div><ResponsiveContainer width="100%" height={250}><BarChart data={rDist}><CartesianGrid strokeDasharray="3 3" stroke="#1f2937"/><XAxis dataKey="rating" tick={{fill:'#6b7280',fontSize:11}}/><YAxis tick={{fill:'#6b7280',fontSize:10}}/><Tooltip content={CTooltip}/><Bar dataKey="count" name="Films" radius={[4,4,0,0]} cursor="pointer" onClick={function(d){sSR(function(p){return p===parseFloat(d.rating)?null:parseFloat(d.rating)})}}>{rDist.map(function(d,i){var r=parseFloat(d.rating),a=sR===r;return <Cell key={i} fill={rC(r)} fillOpacity={sR!==null&&!a?0.15:1} stroke={a?'#fff':'none'} strokeWidth={a?2:0}/>})}</Bar></BarChart></ResponsiveContainer></div>{sR!==null&&<FilmList title={sR+'★'} films={selFilms} onClose={function(){sSR(null)}}/>}</div>}

    {tab==='where'&&<div className="space-y-4"><div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><div className="flex justify-between items-center mb-3"><h3 className="text-sm font-semibold text-gray-300">Platforms</h3><SrtB val={sorts.pl} onToggle={function(){ts('pl')}}/></div><CTbl data={platD} sel={sP} onSel={function(v){sSP(v);sSVe(null)}} sortMode={sorts.pl}/></div><FilmList title={sP} films={platF} onClose={function(){sSP(null)}}/><div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><div className="flex justify-between items-center mb-3"><h3 className="text-sm font-semibold text-gray-300">Theaters</h3><SrtB val={sorts.ve} onToggle={function(){ts('ve')}}/></div><div className="max-h-96 overflow-y-auto"><CTbl data={venD} sel={sVe} onSel={function(v){sSVe(v);sSP(null)}} sortMode={sorts.ve}/></div></div><FilmList title={sVe} films={venF} onClose={function(){sSVe(null)}}/></div>}

    {tab==='who'&&<div className="space-y-4"><div className="grid grid-cols-2 gap-3"><SC label="Solo" value={solo.solo} sub={(ef.length?((solo.solo/ef.length)*100).toFixed(0):0)+'%'} yoy={yoy&&fY(-yoy.fr,'pp')}/><SC label="With Friends" value={solo.social} sub={(ef.length?((solo.social/ef.length)*100).toFixed(0):0)+'%'} yoy={yoy&&fY(yoy.fr,'pp')}/></div><div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><div className="flex justify-between items-center mb-3"><h3 className="text-sm font-semibold text-gray-300">Companions <span className="text-xs text-gray-600">(hover for top films)</span></h3><SrtB val={sorts.co} onToggle={function(){ts('co')}}/></div><div className="max-h-96 overflow-y-auto"><CTbl data={compD} sel={sCo} onSel={sSCo} sortMode={sorts.co}/></div></div><FilmList title={sCo} films={compF} onClose={function(){sSCo(null)}}/></div>}

    {tab==='taste'&&<div className="space-y-4"><div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><div className="flex justify-between items-center mb-3"><h3 className="text-sm font-semibold text-gray-300">Decades</h3><SrtB val={sorts.de} onToggle={function(){ts('de')}}/></div><CTbl data={decD} sel={sDe} onSel={function(v){sSDe(v);sSTg(null)}} sortMode={sorts.de}/></div><FilmList title={sDe} films={decF} onClose={function(){sSDe(null)}}/><div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><div className="flex justify-between items-center mb-3"><h3 className="text-sm font-semibold text-gray-300">Tags</h3><SrtB val={sorts.tg} onToggle={function(){ts('tg')}}/></div><CTbl data={tagD} sel={sTg} onSel={function(v){sSTg(v);sSDe(null)}} sortMode={sorts.tg}/></div><FilmList title={sTg} films={tagF} onClose={function(){sSTg(null)}}/></div>}

    {tab==='diary'&&<div className="space-y-3"><input className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-300 focus:outline-none focus:border-emerald-500" placeholder="Filter..." value={dSrch} onChange={function(e){sDSrch(e.target.value)}}/><div className="bg-gray-900 rounded-xl border border-gray-800 overflow-hidden"><div className="max-h-screen overflow-y-auto"><table className="w-full text-xs"><thead className="sticky top-0 bg-gray-800"><tr>{[['date','Date'],['name','Film'],['year','Year'],['rating','⭐']].map(function(h){var ac=dSrt.col===h[0];return <th key={h[0]} onClick={function(){sDSrt(function(p){return{col:h[0],asc:p.col===h[0]?!p.asc:h[0]==='name'}})}} className={'text-left py-2 px-2 cursor-pointer '+(ac?'text-emerald-400':'text-gray-400')}>{h[1]}{ac?(dSrt.asc?' ↑':' ↓'):''}</th>})}<th className="text-left py-2 px-2 text-gray-400">Where</th></tr></thead><tbody>{diaryData.map(function(f,i){return <tr key={i} className="border-t border-gray-800/50 hover:bg-gray-800/30"><td className="py-1.5 px-2 text-gray-500 whitespace-nowrap">{f.date}</td><td className="py-1.5 px-2 text-gray-200 truncate max-w-xs">{f.name}{f.rewatch&&<span className="text-amber-500 ml-1">↻</span>}</td><td className="py-1.5 px-2 text-gray-500">{f.year}</td><td className="py-1.5 px-2" style={{color:f.rating?rC(f.rating):'#6b7280'}}>{f.rating!==null?f.rating+'★':'—'}</td><td className="py-1.5 px-2 text-gray-500 truncate max-w-32">{gP(f.tags,fullReg)}</td></tr>})}</tbody></table></div></div></div>}

    {tab==='costs'&&(isAdmin?<div className="space-y-4">
      <div className="bg-gray-900 rounded-xl p-4 border border-gray-800"><div className="flex justify-between items-center mb-3"><h3 className="text-sm font-semibold text-gray-300">📋 Subscription Editor</h3><button onClick={function(){doUpdateSubs(function(p){return p.concat([{id:'s_'+Date.now(),name:'New',platforms:[],periods:[{from:'',to:'',price:0}]}])})}} className="text-xs bg-emerald-700 text-white px-2 py-1 rounded">+</button></div>
        <div className="space-y-2">{subs.map(function(sub){return <div key={sub.id} className="bg-gray-800 rounded-lg p-3"><div className="flex justify-between items-center"><span className="text-sm font-medium text-gray-200">{sub.name}</span><div className="flex gap-1"><button onClick={function(){sCostEs(costEs===sub.id?null:sub.id)}} className="text-xs bg-gray-700 text-gray-300 px-2 py-0.5 rounded">{costEs===sub.id?'Close':'Edit'}</button><button onClick={function(){doUpdateSubs(function(p){return p.filter(function(s){return s.id!==sub.id})});sCostEs(null)}} className="text-xs bg-red-900 text-red-300 px-2 py-0.5 rounded">×</button></div></div>
          {costEs===sub.id&&<div className="space-y-3 mt-3">
            <div className="flex gap-2"><label className="text-xs text-gray-500 w-14">Name</label><input className="flex-1 bg-gray-900 border border-gray-700 rounded px-2 py-1 text-xs text-gray-300" value={sub.name} onChange={function(e){var v=e.target.value;doUpdateSubs(function(p){return p.map(function(s){return s.id===sub.id?Object.assign({},s,{name:v}):s})})}}/></div>
            <div><label className="text-xs text-gray-500 mb-1 block">Platforms (click to toggle)</label><div className="flex flex-wrap gap-1">{paidPlatTags.map(function(t){var isIn=sub.platforms.indexOf(t)!==-1;return <button key={t} onClick={function(){doUpdateSubs(function(p){return p.map(function(s){if(s.id!==sub.id)return s;var np=isIn?s.platforms.filter(function(x){return x!==t}):s.platforms.concat([t]);return Object.assign({},s,{platforms:np})})})}} className={'text-xs px-2 py-1 rounded border '+(isIn?'bg-emerald-700 border-emerald-600 text-white':'bg-gray-900 border-gray-700 text-gray-500')}>{getDn(t,fullReg)}</button>})}<button key="_ts" onClick={function(){doUpdateSubs(function(p){return p.map(function(s){if(s.id!==sub.id)return s;var isIn=s.platforms.indexOf('_theater_sub')!==-1;var np=isIn?s.platforms.filter(function(x){return x!=='_theater_sub'}):s.platforms.concat(['_theater_sub']);return Object.assign({},s,{platforms:np})})})}} className={'text-xs px-2 py-1 rounded border '+(sub.platforms.indexOf('_theater_sub')!==-1?'bg-emerald-700 border-emerald-600 text-white':'bg-gray-900 border-gray-700 text-gray-500')}>🎬 Theater Pass</button></div></div>
            <div><div className="flex justify-between"><label className="text-xs text-gray-500">Periods</label><button onClick={function(){doUpdateSubs(function(p){return p.map(function(s){return s.id===sub.id?Object.assign({},s,{periods:s.periods.concat([{from:'',to:'',price:0}])}):s})})}} className="text-xs text-emerald-500">+</button></div>{sub.periods.map(function(pr,pi){return <div key={pi} className="flex gap-1 items-center flex-wrap mt-1"><input type="month" className="bg-gray-900 border border-gray-700 rounded px-1 py-0.5 text-xs text-gray-300 w-28" value={pr.from} onChange={function(e){var v=e.target.value;doUpdateSubs(function(p){return p.map(function(s){if(s.id!==sub.id)return s;return Object.assign({},s,{periods:s.periods.map(function(x,j){return j===pi?Object.assign({},x,{from:v}):x})})})})}}/><span className="text-xs text-gray-600">→</span><input type="month" className="bg-gray-900 border border-gray-700 rounded px-1 py-0.5 text-xs text-gray-300 w-28" placeholder="ongoing" value={pr.to} onChange={function(e){var v=e.target.value;doUpdateSubs(function(p){return p.map(function(s){if(s.id!==sub.id)return s;return Object.assign({},s,{periods:s.periods.map(function(x,j){return j===pi?Object.assign({},x,{to:v}):x})})})})}}/><span className="text-xs text-gray-600">€</span><input type="number" step="0.01" className="bg-gray-900 border border-gray-700 rounded px-1 py-0.5 text-xs text-gray-300 w-14" value={pr.price} onChange={function(e){var v=e.target.value;doUpdateSubs(function(p){return p.map(function(s){if(s.id!==sub.id)return s;return Object.assign({},s,{periods:s.periods.map(function(x,j){return j===pi?Object.assign({},x,{price:parseFloat(v)||0}):x})})})})}}/><span className="text-xs text-gray-600">/mo</span>{sub.periods.length>1&&<button onClick={function(){doUpdateSubs(function(p){return p.map(function(s){return s.id===sub.id?Object.assign({},s,{periods:s.periods.filter(function(_,j){return j!==pi})}):s})})}} className="text-xs text-red-500">×</button>}</div>})}</div>
          </div>}
        </div>})}</div></div>
      {costSummary}
      <DQPanel data={dq}/>
    </div>:costSummary)}

    {tab==='tags'&&isAdmin&&<div className="space-y-4">
      <input className="w-full bg-gray-900 border border-gray-700 rounded-lg px-3 py-2 text-sm text-gray-300 focus:outline-none focus:border-emerald-500" placeholder="🔍 Filter tags..." value={tagSearch} onChange={function(e){sTagSearch(e.target.value)}}/>
      {CATS.map(function(cat){var tags=tagGroupedDash[cat];if(!tags||!tags.length)return null;return <div key={cat} className={'rounded-xl p-4 border mb-3 '+CI[cat].bg}><h3 className={'text-sm font-semibold mb-2 '+CI[cat].c}>{CI[cat].l} ({tags.length})</h3><div className="space-y-0.5 max-h-64 overflow-y-auto">{tags.map(function(t){return renderTagRow(t,false)})}</div></div>})}
    </div>}

    <div className="mt-8 text-center text-xs text-gray-700">Babylonian's Letterboxd Analytics</div>
  </div></div>);
}
